---
title: "fitR contents"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fitR contents}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
------

```{r setup, echo = FALSE, cache = FALSE}
devtools::load_all(here::here())
library("dplyr")
library("xtable")

data(fluTdc1971)
data(models)
data(epi)

f <- capture.output(tools::Rdindex(find.package("fitR")))

desc <- lapply(f, function(x) {
  s <- strsplit(x, split = " +")
  if (length(s[[1]]) == 1) s[[1]][2] <- ""
  c(s[[1]][1], paste(s[[1]][2:length(s[[1]])], collapse = " "))
})

emptyFirst <- which(vapply(desc, function(x) nchar(x[1]) == 0, TRUE))
for (id in rev(emptyFirst)) {
  desc[[id - 1]][2] <- paste(desc[[id - 1]][2], desc[[id]][2], collapse = " ")
}

desc <- desc[-emptyFirst]

df <- data.frame(t(vapply(desc, function(x) x, c("a", "b")))) %>%
  dplyr::rename(name = X1, desc = X2) %>%
  mutate(desc = sub("^ ", "", desc)) %>%
  dplyr::filter(!grepl("_pomp(_r)?$", name)) %>%
  dplyr::filter(!(name %in% c("distanceOscillation", "testFitModel"))) %>%
  dplyr::filter(!grepl("^mcmcEpi", name)) %>% 
  dplyr::filter(!grepl("^p?mcmcSeit", name)) %>% 
  dplyr::filter(name != "calibrateSmc") 

df$func <- apply(df, 1, function(x) {
  "function" %in% class(get(x[["name"]]))
})

ds <- df %>%
  dplyr::filter(!func) %>%
  dplyr::filter(name == "fluTdc1971" | grepl("^epi", name))

ms <- df %>%
  dplyr::filter(!func) %>%
  dplyr::filter(!(name %in% ds$name))

fs <- df %>%
  dplyr::filter(func)
```

# Functions

```{r func_table, results='asis', echo = FALSE }
print(
  xtable(fs[, 1:2],
    align = c("l", "l", "p{0.7\\textwidth}")
  ),
  comment = FALSE,
  include.rownames = FALSE,
  include.colnames = FALSE,
  hline.after = c()
)
```

# Data sets

```{r data_table, results='asis', echo = FALSE }
print(
  xtable(ds[, 1:2],
    align = c("l", "l", "p{0.7\\textwidth}")
  ),
  comment = FALSE,
  include.rownames = FALSE,
  include.colnames = FALSE,
  hline.after = c()
)
```

# Models

```{r model_table, results='asis', echo = FALSE }
print(
  xtable(ms[, 1:2],
    align = c("l", "l", "p{0.7\\textwidth}")
  ),
  comment = FALSE,
  include.rownames = FALSE,
  include.colnames = FALSE,
  hline.after = c()
)
```
